#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

#include "XamlBindingInfo.g.h"

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Button;
                ref class TextBlock;
                ref class Grid;
                ref class TextBox;
                ref class ListView;
            }
        }
    }
}

namespace Just_Editor
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class NewFileDialog : public ::Windows::UI::Xaml::Controls::ContentDialog, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class NewFileDialog_obj1_Bindings;
    
        ::XamlBindingInfo::XamlBindings^ Bindings;
        private: ::Windows::UI::Xaml::Controls::Button^ CloseButton;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ DialogTitle;
        private: ::Windows::UI::Xaml::Controls::Grid^ FileSettingColumn;
        private: ::Windows::UI::Xaml::Controls::Button^ CreateFile_Button;
        private: ::Windows::UI::Xaml::Controls::TextBox^ FileName_TextBox;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ErrorMsg_Block;
        private: ::Windows::UI::Xaml::Controls::ListView^ FileTypeList;
    };
}

