//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "NewFileDialog.xaml.h"

void ::Just_Editor::NewFileDialog::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///NewFileDialog.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}


/// <summary>
/// Auto generated class for compiled bindings.
/// </summary>
class Just_Editor::NewFileDialog::NewFileDialog_obj1_Bindings 
    : public ::XamlBindingInfo::ReferenceTypeXamlBindings<::Just_Editor::NewFileDialog, ::XamlBindingInfo::XamlBindingTrackingBase>
{
public:
    NewFileDialog_obj1_Bindings()
    {
    }

    void Connect(int __connectionId, ::Platform::Object^ __target)
    {
        switch(__connectionId)
        {
            case 5: // NewFileDialog.xaml line 45
                this->obj5 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                break;
            case 6: // NewFileDialog.xaml line 41
                this->obj6 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
                break;
        }
    }

private:
    // Fields for each control that has bindings.
    ::Windows::UI::Xaml::Controls::Button^ obj5;
    ::Windows::UI::Xaml::Controls::TextBlock^ obj6;

    // Update methods for each path node used in binding steps.
    void Update_(::Just_Editor::NewFileDialog^ obj, int phase)
    {
        if (obj != nullptr)
        {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_DialogTitle(obj->DialogTitle, phase);
            }
        }
    }
    void Update_DialogTitle(::Windows::UI::Xaml::Controls::TextBlock^ obj, int phase)
    {
        if (obj != nullptr)
        {
            if ((phase & (NOT_PHASED | (1 << 0))) != 0)
            {
                this->Update_DialogTitle_Foreground(obj->Foreground, phase);
            }
        }
    }
    void Update_DialogTitle_Foreground(::Windows::UI::Xaml::Media::Brush^ obj, int phase)
    {
        if((phase & ((1 << 0) | NOT_PHASED )) != 0)
        {
            // NewFileDialog.xaml line 45
            Set_Windows_UI_Xaml_Controls_Control_Foreground(this->obj5, obj, nullptr);
            // NewFileDialog.xaml line 41
            Set_Windows_UI_Xaml_Controls_TextBlock_Foreground(this->obj6, obj, nullptr);
        }
    }
    static void Set_Windows_UI_Xaml_Controls_Control_Foreground(::Windows::UI::Xaml::Controls::Control^ obj, ::Windows::UI::Xaml::Media::Brush^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Windows::UI::Xaml::Media::Brush^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Windows::UI::Xaml::Media::Brush::typeid, targetNullValue);
        }
        obj->Foreground = value;
    }
    static void Set_Windows_UI_Xaml_Controls_TextBlock_Foreground(::Windows::UI::Xaml::Controls::TextBlock^ obj, ::Windows::UI::Xaml::Media::Brush^ value, ::Platform::String^ targetNullValue)
    {
        if (value == nullptr && targetNullValue != nullptr)
        {
            value = (::Windows::UI::Xaml::Media::Brush^) ::Windows::UI::Xaml::Markup::XamlBindingHelper::ConvertValue(::Windows::UI::Xaml::Media::Brush::typeid, targetNullValue);
        }
        obj->Foreground = value;
    }
};

void ::Just_Editor::NewFileDialog::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            this->CloseButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->CloseButton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Just_Editor::NewFileDialog::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&NewFileDialog::CloseButton_Click);
        }
        break;
    case 3:
        {
            this->DialogTitle = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 4:
        {
            this->FileSettingColumn = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 5:
        {
            this->CreateFile_Button = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->CreateFile_Button))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Just_Editor::NewFileDialog::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&NewFileDialog::CreateFile_Button_Click);
        }
        break;
    case 7:
        {
            this->FileName_TextBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->FileName_TextBox))->TextChanging += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::Controls::TextBox^, ::Windows::UI::Xaml::Controls::TextBoxTextChangingEventArgs^>(this, (void (::Just_Editor::NewFileDialog::*)
                (::Windows::UI::Xaml::Controls::TextBox^, ::Windows::UI::Xaml::Controls::TextBoxTextChangingEventArgs^))&NewFileDialog::FileName_TextBox_TextChanging);
        }
        break;
    case 8:
        {
            this->ErrorMsg_Block = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 9:
        {
            this->FileTypeList = safe_cast<::Windows::UI::Xaml::Controls::ListView^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::ListView^>(this->FileTypeList))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::Just_Editor::NewFileDialog::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&NewFileDialog::FileTypeList_SelectionChanged);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::Just_Editor::NewFileDialog::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    ::XamlBindingInfo::XamlBindings^ bindings = nullptr;
    switch (__connectionId)
    {
        case 1: // NewFileDialog.xaml line 1
            {
                ::Windows::UI::Xaml::Controls::ContentDialog^ element1 = safe_cast<::Windows::UI::Xaml::Controls::ContentDialog^>(__target);
                NewFileDialog_obj1_Bindings* objBindings = new NewFileDialog_obj1_Bindings();
                objBindings->SetDataRoot(this);
                bindings = ref new ::XamlBindingInfo::XamlBindings(objBindings);
                this->Bindings = bindings;
                element1->Loading += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::FrameworkElement^, ::Platform::Object^>(bindings, &::XamlBindingInfo::XamlBindings::Loading);
            }
            break;
    }
    return bindings;
}

#pragma warning(pop)


