//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "StartPage.xaml.h"

void ::Just_Editor::StartPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///StartPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::Just_Editor::StartPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 1:
        {
            ::Windows::UI::Xaml::Controls::Page^ element1 = safe_cast<::Windows::UI::Xaml::Controls::Page^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Page^>(element1))->SizeChanged += ref new ::Windows::UI::Xaml::SizeChangedEventHandler(this, (void (::Just_Editor::StartPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::SizeChangedEventArgs^))&StartPage::Page_SizeChanged);
        }
        break;
    case 2:
        {
            this->MainColumn1 = safe_cast<::Windows::UI::Xaml::Controls::ColumnDefinition^>(__target);
        }
        break;
    case 3:
        {
            this->MainColumn2 = safe_cast<::Windows::UI::Xaml::Controls::ColumnDefinition^>(__target);
        }
        break;
    case 4:
        {
            this->RecentListPanel = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
        }
        break;
    case 5:
        {
            this->NewOptionView = safe_cast<::Windows::UI::Xaml::Controls::GridView^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::GridView^>(this->NewOptionView))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::Just_Editor::StartPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&StartPage::NewOptionView_SelectionChanged);
        }
        break;
    case 6:
        {
            this->OpenOptionView = safe_cast<::Windows::UI::Xaml::Controls::GridView^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::GridView^>(this->OpenOptionView))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::Just_Editor::StartPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&StartPage::OpenOptionView_SelectionChanged);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::Just_Editor::StartPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


