//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "pch.h"
#include "XamlTypeInfo.g.h"

#include "CodeEditor.xaml.h"
#include "DuronWindowItemxaml.xaml.h"
#include "NewFileDialog.xaml.h"
#include "App.xaml.h"
#include "MainPage.xaml.h"
#include "RecentListItem.xaml.h"
#include "RenameDialog.xaml.h"
#include "StartPage.xaml.h"
#include "XamlBindingInfo.g.hpp"
#include "CodeEditor.g.hpp"
#include "DuronWindowItemxaml.g.hpp"
#include "NewFileDialog.g.hpp"
#include "App.g.hpp"
#include "MainPage.g.hpp"
#include "RecentListItem.g.hpp"
#include "RenameDialog.g.hpp"
#include "StartPage.g.hpp"

template<typename T>
::Platform::Object^ ActivateType()
{
    return ref new T;
}

template<typename TInstance, typename TItem>
void CollectionAdd(::Platform::Object^ instance, ::Platform::Object^ item)
{
    safe_cast<TInstance^>(instance)->Append((TItem)item);
}

template<typename TInstance, typename TKey, typename TItem>
void DictionaryAdd(::Platform::Object^ instance, ::Platform::Object^ key, ::Platform::Object^ item)
{
    safe_cast<TInstance^>(instance)->Insert((TKey)key, (TItem)item);
}

template<typename T>
::Platform::Object^ FromStringConverter(::XamlTypeInfo::InfoProvider::XamlUserType^ userType, ::Platform::String^ input)
{
    return ref new ::Platform::Box<T>((T)userType->CreateEnumUIntFromString(input));
}

template<typename TDeclaringType, typename TValue>
::Platform::Object^ GetValueTypeMember_isChanged(::Platform::Object^ instance)
{
    return ref new ::Platform::Box<TValue>(safe_cast<TDeclaringType^>(instance)->isChanged);
}

template<typename TDeclaringType, typename TValue>
::Platform::Object^ GetValueTypeMember_isSelected(::Platform::Object^ instance)
{
    return ref new ::Platform::Box<TValue>(safe_cast<TDeclaringType^>(instance)->isSelected);
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_thisWindowItem(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->thisWindowItem;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_FrameContent(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->FrameContent;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_ItemFile(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->ItemFile;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_OriginalText(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->OriginalText;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_FileName(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->FileName;
}

template<typename TDeclaringType>
::Platform::Object^ GetReferenceTypeMember_FilePath(::Platform::Object^ instance)
{
    return safe_cast<TDeclaringType^>(instance)->FilePath;
}

template<typename TDeclaringType, typename TValue>
void SetValueTypeMember_isChanged(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->isChanged = safe_cast<::Platform::IBox<TValue>^>(value)->Value;
}

template<typename TDeclaringType, typename TValue>
void SetValueTypeMember_isSelected(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->isSelected = safe_cast<::Platform::IBox<TValue>^>(value)->Value;
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_thisWindowItem(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->thisWindowItem = safe_cast<TValue^>(value);
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_FrameContent(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->FrameContent = safe_cast<TValue^>(value);
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_ItemFile(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->ItemFile = safe_cast<TValue^>(value);
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_OriginalText(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->OriginalText = safe_cast<TValue^>(value);
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_FileName(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->FileName = safe_cast<TValue^>(value);
}

template<typename TDeclaringType, typename TValue>
void SetReferenceTypeMember_FilePath(::Platform::Object^ instance, ::Platform::Object^ value)
{
    safe_cast<TDeclaringType^>(instance)->FilePath = safe_cast<TValue^>(value);
}

enum TypeInfo_Flags
{
    TypeInfo_Flags_None                 = 0x00,
    TypeInfo_Flags_IsLocalType          = 0x01,
    TypeInfo_Flags_IsSystemType         = 0x02,
    TypeInfo_Flags_IsReturnTypeStub     = 0x04,
    TypeInfo_Flags_IsBindable           = 0x08,
    TypeInfo_Flags_IsMarkupExtension    = 0x10, 
};

struct TypeInfo
{
    PCWSTR  typeName;
    PCWSTR contentPropertyName;
    ::Platform::Object^ (*activator)();
    void (*collectionAdd)(::Platform::Object^, ::Platform::Object^);
    void (*dictionaryAdd)(::Platform::Object^, ::Platform::Object^, ::Platform::Object^);
    ::Platform::Object^ (*fromStringConverter)(::XamlTypeInfo::InfoProvider::XamlUserType^, ::Platform::String^);
    int     baseTypeIndex;
    int     firstMemberIndex;
    int     firstEnumValueIndex;
    int     createFromStringIndex;
    ::Windows::UI::Xaml::Interop::TypeKind kindofType;
    unsigned int flags;
};

const TypeInfo TypeInfos[] = 
{
    //   0
    L"Object", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //   1
    L"String", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //   2
    L"Boolean", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //   3
    L"Just_Editor.MainPage", L"",
    &ActivateType<::Just_Editor::MainPage>, nullptr, nullptr, nullptr,
    10, // Windows.UI.Xaml.Controls.Page
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //   4
    L"Just_Editor.StartPage", L"",
    &ActivateType<::Just_Editor::StartPage>, nullptr, nullptr, nullptr,
    10, // Windows.UI.Xaml.Controls.Page
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //   5
    L"Just_Editor.CodeEditor", L"",
    &ActivateType<::Just_Editor::CodeEditor>, nullptr, nullptr, nullptr,
    10, // Windows.UI.Xaml.Controls.Page
    0, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //   6
    L"Just_Editor.RenameDialog", L"",
    &ActivateType<::Just_Editor::RenameDialog>, nullptr, nullptr, nullptr,
    13, // Windows.UI.Xaml.Controls.ContentDialog
    1, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //   7
    L"Just_Editor.NewFileDialog", L"",
    &ActivateType<::Just_Editor::NewFileDialog>, nullptr, nullptr, nullptr,
    13, // Windows.UI.Xaml.Controls.ContentDialog
    2, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //   8
    L"Just_Editor.RecentListItem", L"",
    &ActivateType<::Just_Editor::RecentListItem>, nullptr, nullptr, nullptr,
    12, // Windows.UI.Xaml.Controls.UserControl
    3, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //   9
    L"Windows.Storage.StorageFile", L"",
    nullptr, nullptr, nullptr, nullptr,
    0, // Object
    6, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsReturnTypeStub | TypeInfo_Flags_None,
    //  10
    L"Windows.UI.Xaml.Controls.Page", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    6, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //  11
    L"Just_Editor.DuronWindowItemxaml", L"",
    &ActivateType<::Just_Editor::DuronWindowItemxaml>, nullptr, nullptr, nullptr,
    12, // Windows.UI.Xaml.Controls.UserControl
    6, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_IsLocalType | TypeInfo_Flags_None,
    //  12
    L"Windows.UI.Xaml.Controls.UserControl", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    13, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //  13
    L"Windows.UI.Xaml.Controls.ContentDialog", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    13, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //  14
    L"Windows.UI.Xaml.Controls.ContentControl", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1,
    13, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Metadata,
    TypeInfo_Flags_IsSystemType | TypeInfo_Flags_None,
    //  Last type here is for padding
    L"", L"",
    nullptr, nullptr, nullptr, nullptr,
    -1, 
    13, 0, -1, ::Windows::UI::Xaml::Interop::TypeKind::Custom,
    TypeInfo_Flags_None,
};

const UINT TypeInfoLookup[] = { 
      0,   //   0
      0,   //   1
      0,   //   2
      0,   //   3
      0,   //   4
      0,   //   5
      0,   //   6
      2,   //   7
      3,   //   8
      3,   //   9
      3,   //  10
      3,   //  11
      3,   //  12
      3,   //  13
      3,   //  14
      3,   //  15
      3,   //  16
      3,   //  17
      3,   //  18
      3,   //  19
      3,   //  20
      4,   //  21
      5,   //  22
      6,   //  23
      6,   //  24
      7,   //  25
      8,   //  26
      9,   //  27
     10,   //  28
     10,   //  29
     11,   //  30
     11,   //  31
     12,   //  32
     12,   //  33
     12,   //  34
     12,   //  35
     12,   //  36
     13,   //  37
     13,   //  38
     14,   //  39
     15,   //  40
};

struct MemberInfo 
{
    PCWSTR shortName;
    ::Platform::Object^ (*getter)(::Platform::Object^);
    void (*setter)(::Platform::Object^, ::Platform::Object^);
    int typeIndex;
    int targetTypeIndex;
    bool isReadOnly;
    bool isDependencyProperty;
    bool isAttachable;
};

const MemberInfo MemberInfos[] = 
{
    //   0 - Just_Editor.CodeEditor.thisWindowItem
    L"thisWindowItem",
    &GetReferenceTypeMember_thisWindowItem<::Just_Editor::CodeEditor>,
    &SetReferenceTypeMember_thisWindowItem<::Just_Editor::CodeEditor, ::Just_Editor::DuronWindowItemxaml>,
    11, // Just_Editor.DuronWindowItemxaml
    -1,
    false, false, false,
    //   1 - Just_Editor.RenameDialog.FileName
    L"FileName",
    &GetReferenceTypeMember_FileName<::Just_Editor::RenameDialog>,
    &SetReferenceTypeMember_FileName<::Just_Editor::RenameDialog, ::Platform::String>,
    1, // String
    -1,
    false, false, false,
    //   2 - Just_Editor.NewFileDialog.FileName
    L"FileName",
    &GetReferenceTypeMember_FileName<::Just_Editor::NewFileDialog>,
    &SetReferenceTypeMember_FileName<::Just_Editor::NewFileDialog, ::Platform::String>,
    1, // String
    -1,
    false, false, false,
    //   3 - Just_Editor.RecentListItem.ItemFile
    L"ItemFile",
    &GetReferenceTypeMember_ItemFile<::Just_Editor::RecentListItem>,
    &SetReferenceTypeMember_ItemFile<::Just_Editor::RecentListItem, ::Windows::Storage::StorageFile>,
    9, // Windows.Storage.StorageFile
    -1,
    false, false, false,
    //   4 - Just_Editor.RecentListItem.FilePath
    L"FilePath",
    &GetReferenceTypeMember_FilePath<::Just_Editor::RecentListItem>,
    &SetReferenceTypeMember_FilePath<::Just_Editor::RecentListItem, ::Platform::String>,
    1, // String
    -1,
    false, false, false,
    //   5 - Just_Editor.RecentListItem.FileName
    L"FileName",
    &GetReferenceTypeMember_FileName<::Just_Editor::RecentListItem>,
    &SetReferenceTypeMember_FileName<::Just_Editor::RecentListItem, ::Platform::String>,
    1, // String
    -1,
    false, false, false,
    //   6 - Just_Editor.DuronWindowItemxaml.isChanged
    L"isChanged",
    &GetValueTypeMember_isChanged<::Just_Editor::DuronWindowItemxaml, ::Platform::Boolean>,
    &SetValueTypeMember_isChanged<::Just_Editor::DuronWindowItemxaml, ::Platform::Boolean>,
    2, // Boolean
    -1,
    false, false, false,
    //   7 - Just_Editor.DuronWindowItemxaml.isSelected
    L"isSelected",
    &GetValueTypeMember_isSelected<::Just_Editor::DuronWindowItemxaml, ::Platform::Boolean>,
    &SetValueTypeMember_isSelected<::Just_Editor::DuronWindowItemxaml, ::Platform::Boolean>,
    2, // Boolean
    -1,
    false, false, false,
    //   8 - Just_Editor.DuronWindowItemxaml.FrameContent
    L"FrameContent",
    &GetReferenceTypeMember_FrameContent<::Just_Editor::DuronWindowItemxaml>,
    &SetReferenceTypeMember_FrameContent<::Just_Editor::DuronWindowItemxaml, ::Platform::Object>,
    0, // Object
    -1,
    false, false, false,
    //   9 - Just_Editor.DuronWindowItemxaml.ItemFile
    L"ItemFile",
    &GetReferenceTypeMember_ItemFile<::Just_Editor::DuronWindowItemxaml>,
    &SetReferenceTypeMember_ItemFile<::Just_Editor::DuronWindowItemxaml, ::Windows::Storage::StorageFile>,
    9, // Windows.Storage.StorageFile
    -1,
    false, false, false,
    //  10 - Just_Editor.DuronWindowItemxaml.OriginalText
    L"OriginalText",
    &GetReferenceTypeMember_OriginalText<::Just_Editor::DuronWindowItemxaml>,
    &SetReferenceTypeMember_OriginalText<::Just_Editor::DuronWindowItemxaml, ::Platform::String>,
    1, // String
    -1,
    false, false, false,
    //  11 - Just_Editor.DuronWindowItemxaml.FileName
    L"FileName",
    &GetReferenceTypeMember_FileName<::Just_Editor::DuronWindowItemxaml>,
    &SetReferenceTypeMember_FileName<::Just_Editor::DuronWindowItemxaml, ::Platform::String>,
    1, // String
    -1,
    false, false, false,
    //  12 - Just_Editor.DuronWindowItemxaml.FilePath
    L"FilePath",
    &GetReferenceTypeMember_FilePath<::Just_Editor::DuronWindowItemxaml>,
    &SetReferenceTypeMember_FilePath<::Just_Editor::DuronWindowItemxaml, ::Platform::String>,
    1, // String
    -1,
    false, false, false,
};

PCWSTR GetShortName(PCWSTR longName)
{
    PCWSTR separator = wcsrchr(longName, '.');
    return separator != nullptr ? separator + 1: longName;
}

const TypeInfo* GetTypeInfo(::Platform::String^ typeName)
{
    auto typeNameLength = typeName->Length();
    if (typeNameLength < _countof(TypeInfoLookup) - 1)
    {
        for (UINT i = TypeInfoLookup[typeNameLength]; i < TypeInfoLookup[typeNameLength+1]; i++)
        {
            if (typeName == ::Platform::StringReference(TypeInfos[i].typeName))
            {
                return &TypeInfos[i];
            }
        }
    }
    return nullptr;
}

const MemberInfo* GetMemberInfo(::Platform::String^ longMemberName)
{
    auto lastDotIndex = longMemberName->Length();
    while (true)
    {
        if (longMemberName->Data()[lastDotIndex] == '.')
        {
            const TypeInfo* pTypeInfo = GetTypeInfo(ref new ::Platform::String(longMemberName->Data(), lastDotIndex));
            const TypeInfo* pNextTypeInfo = pTypeInfo + 1;
            if (pTypeInfo)
            {
                PCWSTR shortMemberName = GetShortName(longMemberName->Data());
                for (int i = pTypeInfo->firstMemberIndex; i < pNextTypeInfo->firstMemberIndex; i++)
                {
                    if (wcscmp(shortMemberName, MemberInfos[i].shortName) == 0)
                    {
                        return &MemberInfos[i];
                    }
                }
            }
            break;
        }
        if (lastDotIndex == 0)
        {
            break;
        }
        lastDotIndex--;
    }
    return nullptr;
}

::Platform::Collections::Vector<::Windows::UI::Xaml::Markup::IXamlMetadataProvider^>^ ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider::OtherProviders::get()
{
    if(_otherProviders == nullptr)
    {
        auto otherProviders = ref new ::Platform::Collections::Vector<::Windows::UI::Xaml::Markup::IXamlMetadataProvider^>();
        _otherProviders = otherProviders;
    }
    return _otherProviders;
}

::Windows::UI::Xaml::Markup::IXamlType^ ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider::CreateXamlType(::Platform::String^ typeName)
{
    const TypeInfo* pTypeInfo = GetTypeInfo(typeName);
    const TypeInfo* pNextTypeInfo = pTypeInfo + 1;
    if (pTypeInfo == nullptr || pNextTypeInfo == nullptr)
    {
        return nullptr;
    }
    else if (pTypeInfo->flags & TypeInfo_Flags_IsSystemType)
    {
        return ref new ::XamlTypeInfo::InfoProvider::XamlSystemBaseType(typeName);
    }
    else
    {
        ::XamlTypeInfo::InfoProvider::XamlUserType^ userType = ref new ::XamlTypeInfo::InfoProvider::XamlUserType(
            this, 
            ::Platform::StringReference(pTypeInfo->typeName), 
            this->GetXamlTypeByName(::Platform::StringReference(pTypeInfo->baseTypeIndex >= 0 ? TypeInfos[pTypeInfo->baseTypeIndex].typeName : L"")));
        userType->KindOfType = pTypeInfo->kindofType;
        userType->Activator = pTypeInfo->activator;
        userType->CollectionAdd = pTypeInfo->collectionAdd;
        userType->DictionaryAdd = pTypeInfo->dictionaryAdd;
        userType->FromStringConverter = pTypeInfo->fromStringConverter;
        userType->ContentPropertyName = ::Platform::StringReference(pTypeInfo->contentPropertyName);
        userType->IsLocalType = pTypeInfo->flags & TypeInfo_Flags_IsLocalType;
        userType->IsReturnTypeStub = pTypeInfo->flags & TypeInfo_Flags_IsReturnTypeStub;
        userType->IsBindable = pTypeInfo->flags & TypeInfo_Flags_IsBindable;
        userType->IsMarkupExtension = pTypeInfo->flags & TypeInfo_Flags_IsMarkupExtension;
        userType->CreateFromStringMethod = nullptr;
        int nextMemberIndex = pTypeInfo->firstMemberIndex;
        for (int i=pTypeInfo->firstMemberIndex; i < pNextTypeInfo->firstMemberIndex; i++)
        {
            userType->AddMemberName(::Platform::StringReference(MemberInfos[i].shortName));
            nextMemberIndex++;
        }
        return userType;
    }
}

::Windows::UI::Xaml::Markup::IXamlMember^ ::XamlTypeInfo::InfoProvider::XamlTypeInfoProvider::CreateXamlMember(::Platform::String^ longMemberName)
{
    ::XamlTypeInfo::InfoProvider::XamlMember^ xamlMember = nullptr;
    const MemberInfo* pMemberInfo = GetMemberInfo(longMemberName);
    if (pMemberInfo != nullptr)
    {
        xamlMember = ref new ::XamlTypeInfo::InfoProvider::XamlMember(
            this,
            ::Platform::StringReference(pMemberInfo->shortName),
            ::Platform::StringReference(TypeInfos[pMemberInfo->typeIndex].typeName));
        xamlMember->Getter = pMemberInfo->getter;
        xamlMember->Setter = pMemberInfo->setter;
        xamlMember->TargetTypeName = pMemberInfo->targetTypeIndex >= 0 ? ::Platform::StringReference(TypeInfos[pMemberInfo->targetTypeIndex].typeName) : L"";
        xamlMember->IsReadOnly = pMemberInfo->isReadOnly;
        xamlMember->IsDependencyProperty = pMemberInfo->isDependencyProperty;
        xamlMember->IsAttachable = pMemberInfo->isAttachable;
    }
    return xamlMember;
}

